# Generated by Django 2.0.7 on 2018-08-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(help_text='Price of product in cents')),
                ('start_date', models.DateField(help_text='first day price goes is valid')),
                ('end_date', models.DateField(null=True, help_text='last day when price is valid')),
                ('sale_price', models.BooleanField(help_text='indicates a sale price (like Black Friday, etc.)')),
                ('product', models.ManyToManyField(to='products.Product')),
            ],
        ),
    ]
